<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="YZAKAREYA" ignored="4" name="Test On Chrome" tests="4" failures="1" timestamp="2021-02-25T05:36:59 EET" time="58.869" errors="0">
  <testcase name="navigateToSignUpPage" time="5.641" classname="tests.signUpTest"/>
  <testcase name="fillSignUpForm" time="3.827" classname="tests.signUpTest"/>
  <testcase name="addAllAvailableItemsIntoCart" time="15.43" classname="tests.addAllAvailableItemsIntoCartTest"/>
  <testcase name="validateCheckOutItems" time="5.311" classname="tests.checkOutTest">
    <failure type="java.lang.AssertionError" message="expected [196.38] but found [196.37999]">
      <![CDATA[java.lang.AssertionError: expected [196.38] but found [196.37999]
at tests.checkOutTest.validateCheckOutItems(checkOutTest.java:62)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- validateCheckOutItems -->
  <testcase name="@BeforeTest setup" time="0.0" classname="BasePackage.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeTest setup -->
  <testcase name="@BeforeTest setup" time="0.0" classname="BasePackage.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeTest setup -->
  <testcase name="@AfterTest teardown" time="0.0" classname="BasePackage.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterTest teardown -->
  <testcase name="@AfterTest teardown" time="0.0" classname="BasePackage.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterTest teardown -->
</testsuite> <!-- Test On Chrome -->
